name: test-suite
on: [push]
jobs:
  lint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dev-environment
        with:
          py-version: ${{matrix.py-version}}
      - name: format-check
        run: black --check --verbose --diff hvac/
      - name: type-check
        run: mypy --strict hvac/

  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        py-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-dev-environment
        with:
          py-version: ${{matrix.py-version}}
      - name: run-pytest
        run: python -m pytest
